name: Quality Assurance

on:
  pull_request:
    branches: [main]

jobs:
  mago:
    name: Run Mago
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout code
          uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Mago
        run: |
          composer github:fmt
          composer github:lint

  phpstan:
    name: Perform Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Mago
        run: composer github:analyse

  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4]
        stability: [prefer-stable]

    name: Run Tests - P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo

      - name: Install dependencies
        run: |
          composer global require php-coveralls/php-coveralls
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: composer github:test